name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack ./src/JsonWebKeyCreator.ConsoleApp/JsonWebKeyCreator.ConsoleApp.csproj --configuration "Release" --output ./artifacts
    - name: Push
      run: dotnet nuget push ./artifacts/RW7.DotNetSecurityTools.JsonWebKeyCreator.nupkg --source https://api.nuget.org/v3/index.json
