name: .NET Branch

on:
  push:
    branches-ignore: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME_ANEMPTYREECE }}
        password: ${{ secrets.DOCKER_HUB_TOKEN_ANEMPTYREECE }}

    - name: Build container
      uses: docker/build-push-action@v2.7.0
      with:
        file: src/WebApp/Dockerfile
        context: .
        platforms: linux/amd64
        push: true
        tags: anemptyreece/dotnet-security-tools:dev

